Repository Yapp-17th/Web_2_Client, pull requests merged in 2020-12, with the labels that each got.

#71 혼자 연습하기 로딩 및 연습 페이지 제작
  .storybook/manager.js
  .storybook/preview-head.html
  package-lock.json
  package.json
  public/assets/images/study_background.png
  src/App.js
  src/components/AnswerBox/AnswerBox.js
  src/components/AnswerBox/AnswerBox.stories.js
  src/components/AnswerBox/index.js
  src/components/Button/Button.js
  src/components/CamView/CamView.js
  src/components/ConferenceButton/ConferenceButton.js
  src/components/QuestionCardView/QuestionCardView.js
  src/components/QuestionTextBox/QeustionsTextBox.stories.js
  src/components/QuestionTextBox/QuestionTextBox.js
  src/components/QuestionTextBox/index.js
  src/components/Rangebar/RangeBar.js
  src/components/RemainTime/RemainTime.js
  src/components/RemainTime/RemainTime.stories.js
  src/components/RemainTime/RemainTime.test.js
  src/components/RemainTime/index.js
  src/components/Sidebar/Sidebar.js
  src/components/StudyCardView/StudyCardView.js
  src/components/TextBox/TextBox.js
  src/components/TextBox/TextBox.stories.js
  src/components/TextBox/index.js
  src/components/ToggleButton/ToggleButton.js
  src/components/ToggleButton/ToggleButton.stories.js
  src/context/serverContext.js
  src/hooks/useMediaRecorder.js
  src/hooks/useWindowSize.js
  src/mocks/QuestionItemMock.js
  src/mocks/QuestionListMock.js
  src/pages/AloneQuestionCheckList/AloneQuestionCheckList.js
  src/pages/AloneQuestionCheckList/AloneQuestionCheckList.stories.js
  src/pages/LoginPage/LoginPage.js
  src/pages/QuestionListPage/IsQuestionList/IsQuestionList.js
  src/pages/QuestionListPage/IsQuestionList/index.js
  src/pages/QuestionListPage/NoList/NoList.js
  src/pages/QuestionListPage/NoList/index.js
  src/pages/QuestionListPage/QuestionListPage.js
  src/pages/QuestionListPage/index.js
  src/pages/QuestionPage/QuestionPage.js
  src/pages/QuestionPage/index.js
  src/pages/SelfTrainPage/SelfTrainPage.js
  src/pages/SelfTrainPage/SelfTrainPage.stories.js
  src/pages/SelfTrainPage/SelfTrainPage.style.js
  src/pages/SelfTrainPage/index.js
  src/pages/SelfTrainPage/qnaListFixture.js
  src/pages/SelfTrainPage/transitionFixture.js
  src/repository/loginRepository.js
  src/repository/questionListRepository.js
  src/repository/requestVideoRepository.js
  src/store/Auth/auth.js
  src/store/Time/time.js
  src/store/Train/train.js
  src/store/index.js
  webpack.config.js
Labels: 🏁 feature

#79 Sidebar 호버시 디자인 적용 부분 퍼블리싱 완성
  public/assets/images/witherview_logo.png
  public/assets/images/witherview_logo_title.png
  src/assets/images/witherview_logo.png
  src/assets/images/witherview_logo_title.png
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/SidebarButton/SidebarButton.js
Labels: 🌈 style

#83 로그인 화면 퍼블리싱
  .DS_Store
  public/assets/images/witherview_logo_title_dark.png
  src/assets/images/witherview_logo_title_dark.png
  src/components/Checkbox/Checkbox.js
  src/components/InputBar/InputBar.js
  src/pages/LoginPage/LoginPage.js
  src/pages/LoginPage/LoginPage.stories.js
Labels: 🌈 style

#91 Webpack alias를 지정하여 경로 지정을 간편하게 하도록 함
  .eslintrc.js
  .storybook/webpack.config.js
  package-lock.json
  package.json
  public/assets/images/icons.png
  public/assets/images/illust_1.png
  public/assets/images/illust_2.png
  public/assets/images/illust_3.png
  public/assets/images/illust_4.png
  public/assets/images/profile_example.png
  public/assets/images/witherview_logo.png
  public/assets/images/witherview_logo_title.png
  public/assets/images/witherview_logo_title_dark.png
  src/assets/images/study_background.png
  src/components/AuthRoute/AuthRoute.js
  src/components/CamView/CamView.stories.js
  src/components/ConferenceButton/ConferenceButton.js
  src/components/Icon/Icon.js
  src/components/Modal/Modal.js
  src/components/ProfileIcon/ProfileIcon.js
  src/components/ProfileIcon/ProfileIcon.stories.js
  src/components/ProfileIcon/ProfileIcon.test.js
  src/components/ProfileInfoContainer/ProfileInfoContainer.js
  src/components/ProfileMenuContainer/ProfileMenuContainer.js
  src/components/Question/QuestionList/QuestionList.js
  src/components/RemainTime/RemainTime.js
  src/components/Sidebar/Sidebar.js
  src/components/TimeButton/TimeButton.js
  src/hooks/useMediaRecorder.js
  src/pages/AloneQuestionCheckList/AloneQuestionCheckList.js
  src/pages/LoginPage/LoginPage.js
  src/pages/QuestionListPage/IsQuestionList/IsQuestionList.js
  src/pages/QuestionListPage/NoList/NoList.js
  src/pages/QuestionListPage/QuestionListPage.js
  src/pages/QuestionPage/QuestionPage.js
  src/pages/SelfTrainEntry/SelectCard.js
  src/pages/SelfTrainEntry/SelfTrainEntry.js
  src/pages/SelfTrainPage/SelfTrainPage.js
  src/pages/SelfTrainSettingPage/SelfTrainSettingPage.js
  src/store/Modal/modal.js
  src/stories/addon.js
  webpack.config.js
Labels: ⚙ environment

#95 랜딩페이지 작성
  .eslintrc.js
  src/App.js
  src/assets/images/box_c_one.png
  src/assets/images/box_c_three.png
  src/assets/images/box_c_two.png
  src/assets/images/landing_bottom.png
  src/assets/images/landing_top.png
  src/assets/images/middle_craousal_one.png
  src/assets/images/middle_craousal_three.png
  src/assets/images/middle_craousal_two.png
  src/assets/images/middle_end_background.png
  src/assets/images/middle_first.png
  src/components/Button/Button.js
  src/components/InputBar/InputBar.js
  src/components/TextButton/TextButtonProps.js
  src/components/index.js
  src/pages/LandingPage/LandingBottom.js
  src/pages/LandingPage/LandingFooter.js
  src/pages/LandingPage/LandingHeader.js
  src/pages/LandingPage/LandingMiddleOne.js
  src/pages/LandingPage/LandingMiddleThree.js
  src/pages/LandingPage/LandingMiddleTwo.js
  src/pages/LandingPage/LandingPage.js
  src/pages/LandingPage/LandingPage.stories.js
  src/pages/LandingPage/LandingTop.js
  src/pages/LandingPage/components/CircleButton.js
  src/pages/LandingPage/components/TextBoxA.js
  src/pages/LandingPage/components/TextBoxB.js
  src/pages/LandingPage/components/TextBoxC.js
  src/pages/LandingPage/index.js
Labels: 🌈 style, 🏁 feature

#88 체크리스트 텍스트 내용 수정
  .eslintrc.js
  src/mocks/EvaluationListMock.js
  src/pages/AloneQuestionCheckList/AloneQuestionCheckList.js
  src/pages/LoginPage/LoginPage.js
Labels: 🙋‍♂️ question🙋‍♀️, 🛠 fix

#93 로그인 - 면접 질문 가이드 - 혼자연습 환경설정 - 혼자연습 진행 - 체크리스트 유기적으로 동작하도록 연결
  .babelrc
  favicon.png
  package-lock.json
  package.json
  src/App.js
  src/components/Button/Button.js
  src/components/Checkbox/Checkbox.js
  src/components/InputBar/InputBar.js
  src/components/Modal/QuestionListSaveModal/QuestionListSaveModal.js
  src/components/Modal/SelfTrainStartModal/SelfTrainStartModal.js
  src/components/ProfileMenuContainer/ProfileMenuContainer.js
  src/components/Question/QuestionItem/QuestionItem.js
  src/components/Question/QuestionList/QuestionList.js
  src/components/QuestionCardView/QuestionCardView.js
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/SidebarButton/SidebarButton.js
  src/components/TimeButton/TimeButton.js
  src/hooks/useMediaRecorder.js
  src/pages/AloneQuestionCheckList/AloneQuestionCheckList.js
  src/pages/LandingPage/LandingMiddleThree.js
  src/pages/LandingPage/LandingPage.js
  src/pages/LoginPage/LoginPage.js
  src/pages/QuestionListPage/IsQuestionList/IsQuestionList.js
  src/pages/QuestionListPage/QuestionListPage.js
  src/pages/QuestionPage/QuestionPage.js
  src/pages/SelfTrainEntry/index.js
  src/pages/SelfTrainEntryPage/SelectCard.js
  src/pages/SelfTrainEntryPage/SelfTrainEntryPage.js
  src/pages/SelfTrainEntryPage/SelfTrainEntryPage.stories.js
  src/pages/SelfTrainEntryPage/index.js
  src/pages/SelfTrainPage/SelfTrainPage.js
  src/pages/SelfTrainSettingPage/SelfTrainSettingPage.js
  src/store/Auth/auth.js
  src/store/Time/time.js
  src/store/Train/train.js
  src/utils/snippet.js
  webpack.config.js
Labels: 🏁 feature

#103 면접 스터디 방입장 및 스케쥴창 작업
  src/pages/InterviewStudyEntry/InterviewStudy.style.js
  src/pages/InterviewStudyEntry/InterviewStudyEntry.js
  src/pages/InterviewStudyEntry/InterviewStudyEntry.stories.js
  src/pages/InterviewStudyEntry/UsersSection.js
  src/pages/InterviewStudyEntry/index.js
  src/repository/interviewStudyRepository.js
Labels: 🏁 feature

#109 영상 업로드 부분 변경점 및 반응형 디자인 적용
  src/App.js
  src/components/TextBox/TextBox.js
  src/pages/AloneQuestionCheckList/AloneQuestionCheckList.js
  src/pages/LandingPage/LandingTop.js
  src/pages/LoginPage/LoginPage.js
  src/pages/SelfTrainEntryPage/SelfTrainEntryPage.js
  src/pages/SelfTrainPage/SelfTrainPage.js
  src/repository/requestVideoRepository.js
  src/store/Train/train.js
Labels: 🌈 style, 🏁 feature, 🛠 fix

#119 면접스터디 채팅화면 구현
  src/components/ChatInput/ChatInput.js
  src/components/ChatInput/ChatInput.stories.js
  src/components/ChatInput/index.js
  src/components/IntervieweChat/InterviewChat.stories.js
  src/components/IntervieweChat/IntervieweChat.js
  src/components/IntervieweChat/index.js
Labels: 🏁 feature

#134 홈페이지 초기 로딩 속도 개선
  .gitignore
  __mock-server/Procfile
  __mock-server/server.js
  package-lock.json
  package.json
  public/fonts/AppleSDGothicNeoB.ttf
  public/fonts/AppleSDGothicNeoB.woff2
  public/fonts/AppleSDGothicNeoEB.ttf
  public/fonts/AppleSDGothicNeoEB.woff2
  public/fonts/AppleSDGothicNeoM.ttf
  public/fonts/AppleSDGothicNeoM.woff2
  public/fonts/TitilliumWeb-Bold.ttf
  public/fonts/TitilliumWeb-Bold.woff2
  public/fonts/TitilliumWeb-Regular.ttf
  public/fonts/TitilliumWeb-Regular.woff2
  src/App.js
  src/components/ConferenceButton/ConferenceButton.js
  src/components/ConferenceButton/index.js
  src/components/index.js
  src/index.scss
  src/pages/ConferenceRoom/ConferenceRoom.js
  src/pages/ConferenceRoom/PeerVideo.js
  src/pages/ConferenceRoom/index.js
  webpack.config.prod.js
Labels: ⚙ environment, 🚑 bug, 🛠 fix

#135 은비님 결정 하에 AppleGothicNeo 폰트를 SpoqaHansNeo로 변경
  .storybook/preview-head.html
  public/fonts/AppleSDGothicNeoB.woff2
  public/fonts/AppleSDGothicNeoEB.woff2
  public/fonts/AppleSDGothicNeoM.woff2
  public/fonts/Spoqa Han Sans Neo Bold.woff2
  public/fonts/Spoqa Han Sans Neo Medium.woff2
  public/fonts/Spoqa Han Sans Neo Regular.woff2
  src/index.scss
Labels: 🛠 fix

#136 마감 전 vh 기준 디자인 적용
  src/App.js
  src/components/IconTemp.js
  src/components/ProfileEdit/ProfileEdit.js
  src/components/ProfileIcon/ProfileIcon.js
  src/components/ProfileInfoContainer/ProfileInfoContainer.js
  src/components/ProfileMenuContainer/ProfileMenuContainer.js
  src/components/Sidebar/Sidebar.js
  src/components/Sidebar/SidebarButton/SidebarButton.js
  src/pages/AloneQuestionCheckList/AloneQuestionCheckList.js
  src/pages/MyPage/Box/Box.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.style.js
  src/pages/SelfTrainEntryPage/SelectCard.js
  src/pages/SelfTrainPage/SelfTrainPage.js
Labels: 🌈 style, 🛠 fix

#142 모바일 환경에 대응하여 Login Page 및 화면비 경고 페이지 수정
  src/pages/FragileRatio/FragileRatio.js
  src/pages/LoginPage/LoginPage.js
Labels: 🌈 style
